---
- name: Update resolve.conf
  template:
    force: yes
    src: resolve.conf.j2
    dest: /etc/resolve.conf

- name: Install common packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
      - wget
      - curl
      - git
