- name: Checkout code
  git:
    repo: "https://github.com/shimaaaa/django-ansible.git"
    dest: "{{ app.install_directory }}"

- name: Add poetry
  shell: ~/.pyenv/shims/pip install poetry
  args:
    chdir: "{{ app.install_directory }}"

- name: Set poetry config
  shell: ~/.pyenv/shims/poetry config virtualenvs.in-project true
  args:
    chdir: "{{ app.install_directory }}"
  changed_when: False

- name: Poetry install
  shell: ~/.pyenv/shims/poetry install
  args:
    chdir: "{{ app.install_directory }}"

- name: Copy uwsgi service
  copy:
    src: ../files/djtest.uwsgi.service
    dest: /etc/systemd/system/
  become: yes

- name: Systemd daemon-reload
  command: systemctl daemon-reload
  become: yes

- name: Enable uwsgi
  command: systemctl enable djtest.uwsgi.service
  become: yes

- name: Restart uWSGI
  service: name=djtest.uwsgi.service
    state=restarted
  become: yes
